# Generated by Django 6.0.3 on 2026-03-23 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvoted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='base.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
